apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentity.fullname" . }}
  labels:
    {{- include "agentity.labels" . | nindent 4 }}
type: Opaque
data:
  AGENTITY_AUTH_ADMIN_API_KEY: {{ required "adminApiKey must be set in values.yaml" .Values.adminApiKey | b64enc | quote }}
  {{- if .Values.cryptoRootKey }}
  AGENTITY_CRYPTO_ROOT_KEY: {{ .Values.cryptoRootKey | b64enc | quote }}
  {{- else }}
  AGENTITY_CRYPTO_ROOT_KEY: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.password }}
  AGENTITY_REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.config.store.type "postgres" }}
  AGENTITY_STORE_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=disable" .Values.postgresql.user .Values.postgresql.password .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database | b64enc | quote }}
  {{- end }}
